/// SKSU Degree Programs per campus (short names for dropdown)
/// Source: https://sksu.edu.ph/degree-programs/
const Map<String, List<String>> campusPrograms = {
  'access': [
    'BEEd - Elementary Education',
    'BSEd - English',
    'BSEd - Filipino',
    'BSEd - Science',
    'BSEd - Mathematics',
    'BSEd - Social Studies',
    'BPE - Physical Education',
    'BSN - Nursing',
    'BS Midwifery',
    'BS Medical Technology',
    'BS Criminology',
    'BS Industrial Security & Management',
    'Doctor of Medicine',
    'PhD - Educational Management & Leadership',
    'PhD - Public Management',
    'MPM - Public Management',
    'MAEd - Educational Management',
    'MAT - English',
    'MAT - Filipino',
    'MAT - Science',
    'MAT - Mathematics',
    'MAT - Social Studies',
    'MAT - Physical Education',
    'MAT - Livelihood & Technology Education',
    'MIT - Information Technology',
  ],
  'isulan': [
    'BS Computer Science',
    'BS Information Technology',
    'BS Information Systems',
    'BS Civil Engineering',
    'BS Computer Engineering',
    'BS Electronics Engineering',
    'BIndT - Automotive Technology',
    'BIndT - Electrical Technology',
    'BIndT - Drafting Technology',
    'BIndT - Civil Technology',
    'BIndT - Electronics Technology',
    'BIndT - Food Innovation & Culinary Tech',
    'BTVTE - Automotive Technology',
    'BTVTE - Electrical Technology',
    'BTVTE - Drafting Technology',
    'BTVTE - Civil Technology',
    'BTVTE - Electronics Technology',
    'BTVTE - Food & Service Management',
  ],
  'tacurong': [
    'BA Economics',
    'BA Political Science',
    'BS Accountancy',
    'BS Accounting Information System',
    'BS Biology',
    'BS Entrepreneurship',
    'BS Environmental Science',
    'BS Hospitality Management',
    'BS Management Accounting',
    'BS Tourism Management',
  ],
  'kalamansig': [
    'BS Biology - Plant Biology',
    'BS Criminology',
    'BS Fisheries',
    'BS Information Technology',
    'BEEd - Elementary Education',
    'BSEd - Filipino',
    'BSEd - English',
    'BSEd - Science',
    'BSEd - Mathematics',
  ],
  'lutayan': [
    'BEEd - Elementary Education',
    'BSA - Crop Science',
    'BSA - Soil Science',
    'BSA - Crop Protection',
    'BSA - Animal Science',
  ],
  'palimbang': [
    'BEEd - Elementary Education',
    'BS Agribusiness',
  ],
  'bagumbayan': [
    'BS Agribusiness',
    'BTLEd - Agri-Fishery Arts',
  ],
};

List<String> getProgramsForCampus(String campusId) {
  return campusPrograms[campusId] ?? [];
}
